### ISSUE TITLE
Runtimes must be updated

### ISSUE THREAD

**Issue by daniel-bravo** [PacktPublishing/AWS-CDK-in-Action#7]
In chapter 5, I have found several issues when pushing the code into prod and dev. CDK starts the deployment of the infrastructure, however it get stuck in a custom lambda because it says it is made to run on node js 14, which is no longer supported by AWS. Would it be possible to update the code to run lambdas in supported versions

**Comment by jpnws** [comment]
I encountered this issue as well just now. I executed `npx npm-check-updates -u` to update all the npm packages for the infrastructure and am no longer encounter the issue. Unfortunately, I don't know which package was the culprit exactly.

**Comment by rajat-packt** [comment]
Hey @daniel-bravo, please check out the solution mentioned above.
I am closing the issue now, if it does not work for you, please reopen the issue later.
